[meta]
name = "Run History"
author = "Vanawy"
category = "Overlay"
version = "0.10.0"

[script]
dependencies = ["NadeoServices", "MLHook", "MLFeedRaceData"]
optional_dependencies = ["ChampionMedals", "WarriorMedals"]
