[meta]
name        = "Run History"
author      = "Vanawy"
category    = "Overlay"
version     = "0.8.4"

[script]
dependencies = ["MLHook", "MLFeedRaceData"]
optional_dependencies = ["ChampionMedals", "WarriorMedals"]