[meta]
name        = "Run History"
author      = "Vanawy"
category    = "Overlay"
version     = "0.2.3"

[script]
dependencies = ["MLHook", "MLFeedRaceData"]
optional_dependencies = ["ChampionMedals"]